# See https://pre-commit.com/ for usage and config
# pre-commit install
# need commit-msg hook for commitzen
# pre-commit install --hook-type commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: no-commit-to-branch

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-gfm
        exclude: CHANGELOG.md

-   repo: local
    hooks:
    -   id: swift-format
        name: swift-format
        stages: [commit]
        language: system
        entry: swift-format --configuration .swift-format -i -r Sources/
        types: [swift]
        pass_filenames: false
