name: release_github

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag to release as'
        required: false
        type: string
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build universal binary
        run: swift build -c release --arch arm64 --arch x86_64

      - name: Pack up binary
        run: |
          mkdir dist_bin
          zip -q -j dist_bin/markers-extractor-cli.zip .build/release/markers-extractor-cli

      - name: Save binary
        uses: actions/upload-artifact@v2
        with:
          name: release_dist_bin
          path: dist_bin

  release:
    if: github.event_name == 'push' || github.event.inputs.tag != ''
    needs: [build_binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract release changelog
        run: |
          sed "0,/### \[/d;/### \[/Q" CHANGELOG.md > release_changelog
          echo -n "**Full Changelog**: " >> release_changelog
          sed -n 's/### \[.*\](\(.*\)) (.*/\1/p' CHANGELOG.md | head -1 >> release_changelog

      - name: Load release binaries
        uses: actions/download-artifact@v2
        with:
          name: release_dist_bin
          path: dist

      - name: Create Release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release_changelog
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

      - name: Create Release (Custom Tag)
        if: github.event_name != 'push' && github.event.inputs.tag != ''
        uses: ncipollo/release-action@v1
        with:
          bodyFile: release_changelog
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ github.event.inputs.tag }}
